name: "Firebase hosting CI/CD"
on:
  schedule:
    # Release a version everyday at 00:00 UTC every day.
    - cron: '0 0 */1 * *'
  push:
    paths:
      - "src/**"
      - "types/**"
      - "firebase.json"
      - "public/404.html"
      - "index.html"
    branches:
      - "development"
  workflow_dispatch:
    
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: "Checkout to the branch"
        uses: actions/checkout@v3
      - name: "Node.js setup"
        uses: actions/setup-node@v3
        with:
          node-version: 16
      - name: "Install Dependencies (Clean)"
        run: npm ci
      - name: "Build the project"
        run: npm run build
      - name: "Upload the build artifact"
        uses: actions/upload-artifact@v3
        with:
          name: build
          path: build
  
  beta_preview:
    runs-on: ubuntu-latest
    needs: [build]
    if: ${{ github.event_name == 'push' && github.repository_owner == github.triggering_actor && github.ref_name == 'development' }}
    steps:
      - name: "Checkout to the branch"
        uses: actions/checkout@v3
      - name: "Download the build artifact"
        uses: actions/download-artifact@v3
        with:
          name: build
          path: build
      - name: Deploy to firebase
        uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: '${{ secrets.GITHUB_TOKEN }}'
          firebaseServiceAccount: '${{ secrets.FIREBASE_SERVICE_ACCOUNT_FIRE_APPS_7827C }}'
          channelID: beta
          target: birthday-card
          expires: 2d
          projectID: fire-apps-7827c
      - name: "Delete the artifact"
        if: ${{ always() }}
        uses: geekyeggo/delete-artifact@v2
        with:
          name: build
          failOnError: 'false'

  
  live_preview:
    runs-on: ubuntu-latest
    needs: [ build ]
    if: ${{ github.event_name == 'schedule' || github.event_name == 'workflow_dispatch' }}
    steps:
      - name: "Checkout to the branch"
        uses: actions/checkout@v3
      - name: "Download the build artifact"
        uses: actions/download-artifact@v3
        with:
          name: build
          path: build
      - name: Deploy to firebase
        uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: '${{ secrets.GITHUB_TOKEN }}'
          firebaseServiceAccount: '${{ secrets.FIREBASE_SERVICE_ACCOUNT_FIRE_APPS_7827C }}'
          channelID: live
          target: birthday-card
          projectID: fire-apps-7827c
      - name: "Delete the artifact"
        if: ${{ always() }}
        uses: geekyeggo/delete-artifact@v2
        with:
          name: build
          failOnError: 'false'