name: "Firebase hosting"
on:
  push:
    paths:
      - 'src/**'
      - 'types/**'
      - 'index.html'
      - 'public/404.html'
      - 'firebase.json'
      - '*.yml'
    branches:
      - development
jobs:
  # Standard job (no excuses)
  build:
    runs-on: ubuntu-latest
    steps:
      - name: "Node checkout"
        uses: actions/checkout@v3
      - name: "Node install"
        uses: actions/setup-node@v3
        with:
          node-version: 16
      - name: "Install dependencies"
        run: npm ci
      - name: "Build the library"
        run: npm run build
  
  dev_preview:
    runs-on: ubuntu-latest
    needs: build
    if: ${{ github.event_name == 'push' && github.repository_owner == github.triggering_actor && github.ref_name == 'development' }} 
    steps:
      - name: "Node checkout"
        uses: actions/checkout@v3
      - uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: '${{ secrets.GITHUB_TOKEN }}'
          firebaseServiceAccount: '${{ secrets.FIREBASE_SERVICE_ACCOUNT_FIRE_APPS_7827C }}'
          channelId: beta
          target: birthday-card
          expires: 2d
          projectId: fire-apps-7827c